version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - 'config/.env'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rwx
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - 'config/.env'
